// Header Types
export const GET_HEADER_DATA = 'GET_HEADER_DATA';
//DASHBOARD TYPES
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
// Create Task types
export const GET_QUESTION_LIST_DATA = 'GET_QUESTION_LIST_DATA';
export const SET_LOGOUT_TIME = 'SET_LOGOUT_TIME';
export const GET_ADMIN_USER_DATA = 'GET_ADMIN_USER_DATA';
export const LOGIN_SUCCESSFUL_DATA = 'LOGIN_SUCCESSFUL_DATA';
export const GET_QUESTION_SUBMIT_DATA = 'GET_QUESTION_SUBMIT_DATA';